clubfeed/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sites.shortcuts import get_current_site
from django.db.utils import OperationalError
from django.views.i18n import JavaScriptCatalog
from allauth.account.decorators import secure_admin_login

try:
    site = get_current_site(None)
    admin.site.site_header = f"{site.name} administration"
    admin.site.site_title = f"{site.name} site admin"
except OperationalError:
    pass

admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    re_path(r"^comments/", include('django_comments_xtd.urls')),
    # tz_detect
    path("_tz_detect/", include("tz_detect.urls")),
    # avatar
    path("avatar/", include("avatar.urls")),
    # allauth
    path("accounts/", include("allauth.urls")),
    # martor
    path("_martor/", include("martor.urls")),
    # ClubFeed
    path("clubs/", include("clubs.urls")),
    path("create/", include("creator.urls")),
    path("users/", include("users.urls")),
    path("", include("home.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

# Error handlers
handler404 = "core.views.handler_404"

clubs/urls.py
from django.urls import path, include

from clubs.views import (
    view_post,
    club_list,
    club_page,
    edit_club,
    edit_post,
    media_manager,
    edit_media,
)

app_name = "clubs"

urlpatterns = [
    path("<int:club_id>-<slug:club_slug>/", include([
        path("posts/<int:post_id>-<slug:post_slug>/", include([
            path("edit/", edit_post, name="edit_post"),
            path("", view_post, name="view_post"),
        ])),
        path("edit/", edit_club, name="edit_club"),
        path("media/", include([
            path("<int:media_id>/", edit_media, name="edit_media"),
            path("", media_manager, name="media_manager"),
        ])),
        path("", club_page, name="club_page"),
    ])),
    path("", club_list, name="club_list"),
]

creator/urls.py
from django.urls import path, include

from creator.views import create_post

app_name = "creator"

urlpatterns = [
    path("post/", create_post, name="create_post"),
]

home/urls.py
from django.urls import path

from home.views import home

app_name = "home"

urlpatterns = [path("", home, name="home")]

users/urls.py
from django.urls import path, include

from .views import user_page, edit_profile

app_name = "users"

urlpatterns = [
    path(
        "<int:user_id>-<str:username>/",
        include(
            [
                path("edit/", edit_profile, name="edit_profile"),
                path("", user_page, name="user_page"),
            ]
        )
    ),
]

templates/base.html
{% load static %}{% load django_bootstrap5 %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block head_title %}{% endblock head_title %}{{ title }}{% if show_site_name_in_title is not False %} -
    {{ request.site.name }}{% endif %}</title>
  {% if NOINDEX %}<meta name="robots" content="noindex, nofollow">{% endif %}

  <script src="{% static 'scripts/dark.js' %}"></script>

  {% bootstrap_css %}{% bootstrap_javascript %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" integrity="sha384-CK2SzKma4jA5H/MXDUU7i1TqZlCFaD4T01vtyDFvPlD97JQyS+IsSh1nI2EFbpyk" crossorigin="anonymous">
  <script src="https://unpkg.com/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous"></script>

  {# ClubFeed styles are loaded last to override Bootstrap, etc. #}
  <link rel="stylesheet" href="{% static 'styles/base.css' %}">
  <link rel="stylesheet" href="{% static 'styles/markdown.css' %}">

  <link rel="icon" href="{% static 'fav/favicon.svg' %}" type="image/svg+xml">
  <link rel="manifest" href="{% static 'manifest.json' %}">
  <meta name="theme-color" content="#0424c1">
  <meta name="apple-mobile-web-app-title" content="ClubFeed">

  {% block head %}{% endblock head %}
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}"><img id="logo" src="{% static 'logo/sitelogo.svg' %}" alt="ClubFeed home" class="d-inline-block align-top"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a href="{% url 'clubs:club_list' %}" class="nav-link">Clubs</a></li>
            {% if user.is_authenticated %}
              {% if can_post %}
                <li class="nav-item"><a href="{% url 'creator:create_post' %}" class="nav-link">Post</a></li>
              {% endif %}

              {% if user.is_staff %}
                <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link">Admin</a></li>
              {% endif %}
            {% endif %}
          </ul>

          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'users:user_page' user_id=request.user.id username=request.user.username %}" class="nav-link">{{ request.user }}</a>
              </li>
              <li class="nav-item"><a href="{% url 'account_email' %}" class="nav-link">Settings</a></li>
              <li class="nav-item"><a href="{% url 'account_logout' %}" class="nav-link">Sign out</a></li>
            {% else %}
              <li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link">Sign in</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% bootstrap_messages %}
  </header>

  <main id="main">
{% block pre_h1 %}{% endblock %}
  {% if title and h1_from_title is not False %}<h1>{{ title }}</h1>{% endif %}
{% block main %}{% endblock %}
  </main>

{% load tz_detect %}{% tz_detect %}
</body>
</html>

templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
  <div class="mb-3">{{ pre_form|safe }}</div>
  <form method="post"{% if form_data %} enctype="multipart/form-data"{% endif %}>
    {% crispy form %}
  </form>
{% endblock %}