clubfeed/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sites.shortcuts import get_current_site
from django.db.utils import OperationalError
from django.views.i18n import JavaScriptCatalog
from allauth.account.decorators import secure_admin_login

try:
    site = get_current_site(None)
    admin.site.site_header = f"{site.name} administration"
    admin.site.site_title = f"{site.name} site admin"
except OperationalError:
    pass

admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    re_path(r"^comments/", include('django_comments_xtd.urls')),
    # tz_detect
    path("_tz_detect/", include("tz_detect.urls")),
    # avatar
    path("avatar/", include("avatar.urls")),
    # allauth
    path("accounts/", include("allauth.urls")),
    # martor
    path("_martor/", include("martor.urls")),
    # ClubFeed
    path("clubs/", include("clubs.urls")),
    path("create/", include("creator.urls")),
    path("users/", include("users.urls")),
    path("", include("home.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

# Error handlers
handler404 = "core.views.handler_404"

clubs/urls.py
from django.urls import path, include

from clubs.views import (
    view_post,
    club_list,
    club_page,
    edit_club,
    edit_post,
    media_manager,
    edit_media,
)

app_name = "clubs"

urlpatterns = [
    path("<int:club_id>-<slug:club_slug>/", include([
        path("posts/<int:post_id>-<slug:post_slug>/", include([
            path("edit/", edit_post, name="edit_post"),
            path("", view_post, name="view_post"),
        ])),
        path("edit/", edit_club, name="edit_club"),
        path("media/", include([
            path("<int:media_id>/", edit_media, name="edit_media"),
            path("", media_manager, name="media_manager"),
        ])),
        path("", club_page, name="club_page"),
    ])),
    path("", club_list, name="club_list"),
]

home/urls.py
from django.urls import path

from home.views import home

app_name = "home"

urlpatterns = [path("", home, name="home")]

users/urls.py
from django.urls import path, include

from .views import user_page, edit_profile

app_name = "users"

urlpatterns = [
    path(
        "<int:user_id>-<str:username>/",
        include(
            [
                path("edit/", edit_profile, name="edit_profile"),
                path("", user_page, name="user_page"),
            ]
        )
    ),
]

templates/components/post/card.html
{% load markdown_extras %}

<article class="card post-card">
  <span class="poster">
    {{ post.post_date }}
    • in <a href="{% url 'clubs:club_page' club_id=post.club.id club_slug=post.club.slug %}">{{ post.club.name }}</a>
    • by <a href="{% url 'users:user_page' user_id=post.author.id username=post.author.username %}">{{ post.author }}</a>
    • {{ post.upvoters.count }} upvote{{ post.upvoters.count|pluralize }}
  </span>
  <h2>
    <a href="{% url 'clubs:view_post' club_id=post.club.id club_slug=post.club.slug post_id=post.id post_slug=post.slug %}">
      {{ post.title }}
    </a>
  </h2>
  <div class="markdown">
{{ post.body|sanitized_markdown|safe }}
  </div>
</article>